# Site settings
title: Ben Rowe
description: Open source web developer
baseurl: ""
url: "http://benrowe.info"

# User settings
username: Ben Rowe
user_description: About me here!
user_title: Software Developer
email: ben.rowe.83@gmail.com
twitter_username:
github_username: benrowe
gplus_username: benrowe

# Google-analytics
google-analytics:
  id: "UA-18545738-3"

exclude: ['package.json', 'src' , 'node_modules']
